### PR TITLE
async email v1

### PR DESCRIPTION
**Pull request by jrcichra**
Need to test if emails work

### CODE REVIEW

**Comment by jrcichra** [comment]
It works as I expect. The only thing is on control + c it unwraps on emails.rs:100.

**Comment by jrcichra** [comment]
I fixed that by returning on error. Not the best solution but probably good enough.

**Comment by jrcichra** [comment]
The latest diff needs these two environment variables in new versions of Tira:

```
TIRA_EMAIL_DOMAIN=jrcichra.dev
TIRA_EMAIL_SUBDOMAIN=mail
```

**Review by tjcichra — APPROVED** [review]
LGTM!

**Pull request merged**
